environment:
  matrix:
  - TARGET: i686-pc-windows-gnu
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: x86_64-pc-windows-gnu
    OPENSSL: C:\OpenSSL-Win64

install:
  - SET OPENSSL_INCLUDE_DIR=%OPENSSL%\include
  - SET OPENSSL_LIB_DIR=%OPENSSL%\bin
  - dir %OPENSSL%\bin
  - CP %OPENSSL%\bin\ssleay32.dll %OPENSSL%\bin\libssl32.dll
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build
  - cargo test --verbose